blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    path('category/<int:pk>', views.category, name='category'),
    path('tag/<int:pk>', views.tag, name='tag'),
    path('author/<int:pk>', views.author, name='author'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone, html
from django.utils.html import strip_tags
import markdown

# each post belongs to a category, and each category can have multiple posts
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
# each post can have multiple tags, and each tag can have multiple posts
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
# post: title, body, created_time, modified_time, excerpt (allowed to be empty), category, tags, author
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default = 0, editable = False)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import re
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from markdown.extensions.toc import TocExtension
from .models import Post, Category, Tag
import markdown
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    md = markdown.Markdown(extensions=[
                                'markdown.extensions.extra',
                                'markdown.extensions.codehilite',
                                TocExtension(),
                          ])
    post.body = md.convert(post.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''

    return render(request, 'blog/detail.html', context={'post': post})

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def tag(request, pk):
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def author(request, pk):
    auth = get_object_or_404(User, pk=pk)
    post_list = Post.objects.filter(author=auth)
    return render(request, 'blog/index.html', context={'post_list': post_list})

comments/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.contrib import messages
from .forms import CommentForm
from blog.models import Post

# Create your views here.

@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

        messages.add_message(request, messages.SUCCESS, 'Comment submitted successfully!', extra_tags='success')
        return redirect(post)

    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, 'Comment submitted failed!', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

templates/base.html
{% load static %}
{% load blog_extras %}

<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <style>
        .codehilite {
          padding: 0;
        }
    
        /* for block of numbers */
        .hljs-ln-numbers {
          -webkit-touch-callout: none;
          -webkit-user-select: none;
          -khtml-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
    
          text-align: center;
          color: #ccc;
          border-right: 1px solid #CCC;
          vertical-align: top;
          padding-right: 5px;
        }
    
        .hljs-ln-n {
          width: 30px;
        }
    
        /* for block of code */
        .hljs-ln .hljs-ln-code {
          padding-left: 10px;
          white-space: pre;
        }
      </style>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href ="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Dashboard">Dashboard</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
<div class="copyrights">Collect from<a href="http://zmrenwu.com/">zmrenwu</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}{% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}{% endblock toc %}
                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="res" style="margin-top: 10px;">
                    <a href=''><span class="ion-ios-email-outline"></span> Subscribe</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2024 - Collect from <a href="http://zmrenwu.com/"
                                                        target="_blank" title="Template">zmrenwu</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">Dashboard</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>

<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
  <article class="post post-{{ post.pk }}">
    <header class="entry-header">
      <h1 class="entry-title">{{ post.title }}</h1>
      <div class="entry-meta">
        <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
        <span class="post-date"><a><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
        <span class="post-author"><a href="{% url 'blog:author' post.author.pk %}">{{ post.author }}</a></span>
        <span class="comments-link"><a href="#comment-area"> {{ post.comment_set.count }} {{ post.comment_set.count|pluralize:"Comment,Comments" }}</a></span>
        <span class="views-count"><a>{{ post.views }} Read</a></span>
      </div>
    </header>
    <div class="entry-content clearfix">
      {{ post.body | safe }}
    </div>
  </article>
  <section class="comment-area" id="comment-area">
    <hr>
    <h3>Comment</h3>
    {% show_comment_form post %}
    <div class="comment-list">
      {% show_comments post %}
    </div>
  </section>
{% endblock main %}

{% block toc %}
    {% if post.toc %}
        <div class="widget widget-content">
            <h3 class="widget-title">Catalog</h3>
            {{ post.toc | safe }}
        </div>
    {% endif %}
{% endblock toc %}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">Archives</h3>
    <ul>
        {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">{{ date|date:"b"|capfirst }} {{ date.year }}</a>
            </li>
        {% empty %}
            <li>There's no archives yet!</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_authors.html
<div class="widget widget-Authors">
    <h3 class="widget-title">Authors</h3>
    <ul>
        {% for author in Author_list %}
            <li>
                <a href="{% url 'blog:author' author.pk %}">{{ author.name }}</a>
            </li>
        {% empty %}
            <li>This author has no post yet!</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">Category</h3>
    <ul>
        {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.post_count }})</span></a>
            </li>
        {% empty %}
            <li>There's no category yet!</li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">Recent Posts</h3>
    <ul>
        {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
            <li>There's no recent post yet!</li>
        {% endfor %}
    </ul>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">Tag Cloud</h3>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
            </li>
        {% empty %}
            <li>There's no tag yet!</li>
        {% endfor %}
    </ul>

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">\
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
            </header>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a><time class="entry-date"
                                                            datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="{% url 'blog:author' post.author.pk %}">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} {{ post.comment_set.count|pluralize:"Comment,Comments" }}</a></span>
                <span class="views-count"><a>{{ post.views }} Read</a></span>
            </div>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">Continue Reading <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">
            <h2> There's no blog yet! </h2>
        </div>
    {% endfor %}

    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock main %}

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-4">
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}: </label>
        {{ form.name }}
        {{ form.name.errors }}
      </div>
      <div class="col-md-4">
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}: </label>
        {{ form.email }}
        {{ form.email.errors }}
      </div>
      <div class="col-md-4">
        <label for="{{ form.url.id_for_label }}">{{ form.url.label }}: </label>
        {{ form.url }}
        {{ form.url.errors }}
      </div>
      <div class="col-md-12">
        <label for="{{ form.text.id_for_label }}">{{ form.text.label }}: </label>
        {{ form.text }}
        {{ form.text.errors }}
        <button type="submit" class="comment-btn">Submit</button>
      </div>
    </div>    <!-- row -->
  </form>

templates/comments/inclusions/_list.html
<h3><span>{{ comment_count }}</span> Comments</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
        <div class="text">
            {{ comment.text|linebreaks }}
        </div>
        </li>
    {% empty %}
        There's no comment yet!
    {% endfor %}
</ul>

templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block main %}
  {% show_comment_form post form %}
{% endblock main %}